version: 0.2
phases:
  install:
    commands:
      - pip3 install -r requirements-dev.txt
      - pip3 install -r app/requirements-links.txt
      - pip3 install -r app/requirements-app.txt
      - pip3 install -r app/tests/requirements-tests.txt
      - echo done with the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mkdir target
      - date > target/date.out
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/date.out
    - build/*
    - appsec.yml